/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZespolRouteImport } from './routes/zespol'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RealizacjeRouteImport } from './routes/realizacje'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as PolitykaCookiesRouteImport } from './routes/polityka-cookies'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KalkulatorPompyCieplaRouteImport } from './routes/kalkulator-pompy-ciepla'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WiedzaIndexRouteImport } from './routes/wiedza.index'
import { Route as WiedzaCategoryRouteImport } from './routes/wiedza.$category'
import { Route as RealizacjeSlugRouteImport } from './routes/realizacje.$slug'
import { Route as OfertaEnergiaRouteImport } from './routes/oferta.energia'
import { Route as OfertaServiceRouteImport } from './routes/oferta.$service'
import { Route as LabEpisodeSlugRouteImport } from './routes/lab-episode.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as WiedzaCategorySlugRouteImport } from './routes/wiedza.$category.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AuthenticatedAdminNewVideoRouteImport } from './routes/_authenticated.admin.new-video'
import { Route as AuthenticatedAdminNewPdfRouteImport } from './routes/_authenticated.admin.new-pdf'
import { Route as AuthenticatedAdminNewArticleRouteImport } from './routes/_authenticated.admin.new-article'

const ZespolRoute = ZespolRouteImport.update({
  id: '/zespol',
  path: '/zespol',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizacjeRoute = RealizacjeRouteImport.update({
  id: '/realizacje',
  path: '/realizacje',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaCookiesRoute = PolitykaCookiesRouteImport.update({
  id: '/polityka-cookies',
  path: '/polityka-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorPompyCieplaRoute = KalkulatorPompyCieplaRouteImport.update({
  id: '/kalkulator-pompy-ciepla',
  path: '/kalkulator-pompy-ciepla',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaIndexRoute = WiedzaIndexRouteImport.update({
  id: '/wiedza/',
  path: '/wiedza/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaCategoryRoute = WiedzaCategoryRouteImport.update({
  id: '/wiedza/$category',
  path: '/wiedza/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizacjeSlugRoute = RealizacjeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealizacjeRoute,
} as any)
const OfertaEnergiaRoute = OfertaEnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => OfertaRoute,
} as any)
const OfertaServiceRoute = OfertaServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => OfertaRoute,
} as any)
const LabEpisodeSlugRoute = LabEpisodeSlugRouteImport.update({
  id: '/lab-episode/$slug',
  path: '/lab-episode/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WiedzaCategorySlugRoute = WiedzaCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WiedzaCategoryRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminNewVideoRoute =
  AuthenticatedAdminNewVideoRouteImport.update({
    id: '/admin/new-video',
    path: '/admin/new-video',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNewPdfRoute =
  AuthenticatedAdminNewPdfRouteImport.update({
    id: '/admin/new-pdf',
    path: '/admin/new-pdf',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNewArticleRoute =
  AuthenticatedAdminNewArticleRouteImport.update({
    id: '/admin/new-article',
    path: '/admin/new-article',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kalkulator-pompy-ciepla': typeof KalkulatorPompyCieplaRoute
  '/kontakt': typeof KontaktRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/realizacje': typeof RealizacjeRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zespol': typeof ZespolRoute
  '/lab-episode/$slug': typeof LabEpisodeSlugRoute
  '/oferta/$service': typeof OfertaServiceRoute
  '/oferta/energia': typeof OfertaEnergiaRoute
  '/realizacje/$slug': typeof RealizacjeSlugRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza/': typeof WiedzaIndexRoute
  '/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kalkulator-pompy-ciepla': typeof KalkulatorPompyCieplaRoute
  '/kontakt': typeof KontaktRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/realizacje': typeof RealizacjeRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zespol': typeof ZespolRoute
  '/lab-episode/$slug': typeof LabEpisodeSlugRoute
  '/oferta/$service': typeof OfertaServiceRoute
  '/oferta/energia': typeof OfertaEnergiaRoute
  '/realizacje/$slug': typeof RealizacjeSlugRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza': typeof WiedzaIndexRoute
  '/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/kalkulator-pompy-ciepla': typeof KalkulatorPompyCieplaRoute
  '/kontakt': typeof KontaktRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRouteWithChildren
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/realizacje': typeof RealizacjeRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zespol': typeof ZespolRoute
  '/lab-episode/$slug': typeof LabEpisodeSlugRoute
  '/oferta/$service': typeof OfertaServiceRoute
  '/oferta/energia': typeof OfertaEnergiaRoute
  '/realizacje/$slug': typeof RealizacjeSlugRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza/': typeof WiedzaIndexRoute
  '/_authenticated/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/_authenticated/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/_authenticated/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kalkulator-pompy-ciepla'
    | '/kontakt'
    | '/lab'
    | '/login'
    | '/oferta'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/realizacje'
    | '/sitemap.xml'
    | '/zespol'
    | '/lab-episode/$slug'
    | '/oferta/$service'
    | '/oferta/energia'
    | '/realizacje/$slug'
    | '/wiedza/$category'
    | '/wiedza/'
    | '/admin/new-article'
    | '/admin/new-pdf'
    | '/admin/new-video'
    | '/api/public/contact'
    | '/wiedza/$category/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kalkulator-pompy-ciepla'
    | '/kontakt'
    | '/lab'
    | '/login'
    | '/oferta'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/realizacje'
    | '/sitemap.xml'
    | '/zespol'
    | '/lab-episode/$slug'
    | '/oferta/$service'
    | '/oferta/energia'
    | '/realizacje/$slug'
    | '/wiedza/$category'
    | '/wiedza'
    | '/admin/new-article'
    | '/admin/new-pdf'
    | '/admin/new-video'
    | '/api/public/contact'
    | '/wiedza/$category/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kalkulator-pompy-ciepla'
    | '/kontakt'
    | '/lab'
    | '/login'
    | '/oferta'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/realizacje'
    | '/sitemap.xml'
    | '/zespol'
    | '/lab-episode/$slug'
    | '/oferta/$service'
    | '/oferta/energia'
    | '/realizacje/$slug'
    | '/wiedza/$category'
    | '/wiedza/'
    | '/_authenticated/admin/new-article'
    | '/_authenticated/admin/new-pdf'
    | '/_authenticated/admin/new-video'
    | '/api/public/contact'
    | '/wiedza/$category/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KalkulatorPompyCieplaRoute: typeof KalkulatorPompyCieplaRoute
  KontaktRoute: typeof KontaktRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  OfertaRoute: typeof OfertaRouteWithChildren
  PolitykaCookiesRoute: typeof PolitykaCookiesRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RealizacjeRoute: typeof RealizacjeRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZespolRoute: typeof ZespolRoute
  LabEpisodeSlugRoute: typeof LabEpisodeSlugRoute
  WiedzaCategoryRoute: typeof WiedzaCategoryRouteWithChildren
  WiedzaIndexRoute: typeof WiedzaIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zespol': {
      id: '/zespol'
      path: '/zespol'
      fullPath: '/zespol'
      preLoaderRoute: typeof ZespolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realizacje': {
      id: '/realizacje'
      path: '/realizacje'
      fullPath: '/realizacje'
      preLoaderRoute: typeof RealizacjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-cookies': {
      id: '/polityka-cookies'
      path: '/polityka-cookies'
      fullPath: '/polityka-cookies'
      preLoaderRoute: typeof PolitykaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator-pompy-ciepla': {
      id: '/kalkulator-pompy-ciepla'
      path: '/kalkulator-pompy-ciepla'
      fullPath: '/kalkulator-pompy-ciepla'
      preLoaderRoute: typeof KalkulatorPompyCieplaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza/': {
      id: '/wiedza/'
      path: '/wiedza'
      fullPath: '/wiedza/'
      preLoaderRoute: typeof WiedzaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza/$category': {
      id: '/wiedza/$category'
      path: '/wiedza/$category'
      fullPath: '/wiedza/$category'
      preLoaderRoute: typeof WiedzaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realizacje/$slug': {
      id: '/realizacje/$slug'
      path: '/$slug'
      fullPath: '/realizacje/$slug'
      preLoaderRoute: typeof RealizacjeSlugRouteImport
      parentRoute: typeof RealizacjeRoute
    }
    '/oferta/energia': {
      id: '/oferta/energia'
      path: '/energia'
      fullPath: '/oferta/energia'
      preLoaderRoute: typeof OfertaEnergiaRouteImport
      parentRoute: typeof OfertaRoute
    }
    '/oferta/$service': {
      id: '/oferta/$service'
      path: '/$service'
      fullPath: '/oferta/$service'
      preLoaderRoute: typeof OfertaServiceRouteImport
      parentRoute: typeof OfertaRoute
    }
    '/lab-episode/$slug': {
      id: '/lab-episode/$slug'
      path: '/lab-episode/$slug'
      fullPath: '/lab-episode/$slug'
      preLoaderRoute: typeof LabEpisodeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wiedza/$category/$slug': {
      id: '/wiedza/$category/$slug'
      path: '/$slug'
      fullPath: '/wiedza/$category/$slug'
      preLoaderRoute: typeof WiedzaCategorySlugRouteImport
      parentRoute: typeof WiedzaCategoryRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/new-video': {
      id: '/_authenticated/admin/new-video'
      path: '/admin/new-video'
      fullPath: '/admin/new-video'
      preLoaderRoute: typeof AuthenticatedAdminNewVideoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/new-pdf': {
      id: '/_authenticated/admin/new-pdf'
      path: '/admin/new-pdf'
      fullPath: '/admin/new-pdf'
      preLoaderRoute: typeof AuthenticatedAdminNewPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/new-article': {
      id: '/_authenticated/admin/new-article'
      path: '/admin/new-article'
      fullPath: '/admin/new-article'
      preLoaderRoute: typeof AuthenticatedAdminNewArticleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminNewArticleRoute: typeof AuthenticatedAdminNewArticleRoute
  AuthenticatedAdminNewPdfRoute: typeof AuthenticatedAdminNewPdfRoute
  AuthenticatedAdminNewVideoRoute: typeof AuthenticatedAdminNewVideoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminNewArticleRoute: AuthenticatedAdminNewArticleRoute,
  AuthenticatedAdminNewPdfRoute: AuthenticatedAdminNewPdfRoute,
  AuthenticatedAdminNewVideoRoute: AuthenticatedAdminNewVideoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OfertaRouteChildren {
  OfertaServiceRoute: typeof OfertaServiceRoute
  OfertaEnergiaRoute: typeof OfertaEnergiaRoute
}

const OfertaRouteChildren: OfertaRouteChildren = {
  OfertaServiceRoute: OfertaServiceRoute,
  OfertaEnergiaRoute: OfertaEnergiaRoute,
}

const OfertaRouteWithChildren =
  OfertaRoute._addFileChildren(OfertaRouteChildren)

interface RealizacjeRouteChildren {
  RealizacjeSlugRoute: typeof RealizacjeSlugRoute
}

const RealizacjeRouteChildren: RealizacjeRouteChildren = {
  RealizacjeSlugRoute: RealizacjeSlugRoute,
}

const RealizacjeRouteWithChildren = RealizacjeRoute._addFileChildren(
  RealizacjeRouteChildren,
)

interface WiedzaCategoryRouteChildren {
  WiedzaCategorySlugRoute: typeof WiedzaCategorySlugRoute
}

const WiedzaCategoryRouteChildren: WiedzaCategoryRouteChildren = {
  WiedzaCategorySlugRoute: WiedzaCategorySlugRoute,
}

const WiedzaCategoryRouteWithChildren = WiedzaCategoryRoute._addFileChildren(
  WiedzaCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KalkulatorPompyCieplaRoute: KalkulatorPompyCieplaRoute,
  KontaktRoute: KontaktRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  OfertaRoute: OfertaRouteWithChildren,
  PolitykaCookiesRoute: PolitykaCookiesRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RealizacjeRoute: RealizacjeRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZespolRoute: ZespolRoute,
  LabEpisodeSlugRoute: LabEpisodeSlugRoute,
  WiedzaCategoryRoute: WiedzaCategoryRouteWithChildren,
  WiedzaIndexRoute: WiedzaIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
