/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WiedzaIndexRouteImport } from './routes/wiedza.index'
import { Route as WiedzaCategoryRouteImport } from './routes/wiedza.$category'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as WiedzaCategorySlugRouteImport } from './routes/wiedza.$category.$slug'
import { Route as AuthenticatedAdminNewVideoRouteImport } from './routes/_authenticated.admin.new-video'
import { Route as AuthenticatedAdminNewPdfRouteImport } from './routes/_authenticated.admin.new-pdf'
import { Route as AuthenticatedAdminNewArticleRouteImport } from './routes/_authenticated.admin.new-article'

const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaIndexRoute = WiedzaIndexRouteImport.update({
  id: '/wiedza/',
  path: '/wiedza/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaCategoryRoute = WiedzaCategoryRouteImport.update({
  id: '/wiedza/$category',
  path: '/wiedza/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WiedzaCategorySlugRoute = WiedzaCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WiedzaCategoryRoute,
} as any)
const AuthenticatedAdminNewVideoRoute =
  AuthenticatedAdminNewVideoRouteImport.update({
    id: '/admin/new-video',
    path: '/admin/new-video',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNewPdfRoute =
  AuthenticatedAdminNewPdfRouteImport.update({
    id: '/admin/new-pdf',
    path: '/admin/new-pdf',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNewArticleRoute =
  AuthenticatedAdminNewArticleRouteImport.update({
    id: '/admin/new-article',
    path: '/admin/new-article',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza/': typeof WiedzaIndexRoute
  '/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza': typeof WiedzaIndexRoute
  '/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/wiedza/$category': typeof WiedzaCategoryRouteWithChildren
  '/wiedza/': typeof WiedzaIndexRoute
  '/_authenticated/admin/new-article': typeof AuthenticatedAdminNewArticleRoute
  '/_authenticated/admin/new-pdf': typeof AuthenticatedAdminNewPdfRoute
  '/_authenticated/admin/new-video': typeof AuthenticatedAdminNewVideoRoute
  '/wiedza/$category/$slug': typeof WiedzaCategorySlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/login'
    | '/premium'
    | '/wiedza/$category'
    | '/wiedza/'
    | '/admin/new-article'
    | '/admin/new-pdf'
    | '/admin/new-video'
    | '/wiedza/$category/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab'
    | '/login'
    | '/premium'
    | '/wiedza/$category'
    | '/wiedza'
    | '/admin/new-article'
    | '/admin/new-pdf'
    | '/admin/new-video'
    | '/wiedza/$category/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/lab'
    | '/login'
    | '/premium'
    | '/wiedza/$category'
    | '/wiedza/'
    | '/_authenticated/admin/new-article'
    | '/_authenticated/admin/new-pdf'
    | '/_authenticated/admin/new-video'
    | '/wiedza/$category/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  PremiumRoute: typeof PremiumRoute
  WiedzaCategoryRoute: typeof WiedzaCategoryRouteWithChildren
  WiedzaIndexRoute: typeof WiedzaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza/': {
      id: '/wiedza/'
      path: '/wiedza'
      fullPath: '/wiedza/'
      preLoaderRoute: typeof WiedzaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza/$category': {
      id: '/wiedza/$category'
      path: '/wiedza/$category'
      fullPath: '/wiedza/$category'
      preLoaderRoute: typeof WiedzaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wiedza/$category/$slug': {
      id: '/wiedza/$category/$slug'
      path: '/$slug'
      fullPath: '/wiedza/$category/$slug'
      preLoaderRoute: typeof WiedzaCategorySlugRouteImport
      parentRoute: typeof WiedzaCategoryRoute
    }
    '/_authenticated/admin/new-video': {
      id: '/_authenticated/admin/new-video'
      path: '/admin/new-video'
      fullPath: '/admin/new-video'
      preLoaderRoute: typeof AuthenticatedAdminNewVideoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/new-pdf': {
      id: '/_authenticated/admin/new-pdf'
      path: '/admin/new-pdf'
      fullPath: '/admin/new-pdf'
      preLoaderRoute: typeof AuthenticatedAdminNewPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/new-article': {
      id: '/_authenticated/admin/new-article'
      path: '/admin/new-article'
      fullPath: '/admin/new-article'
      preLoaderRoute: typeof AuthenticatedAdminNewArticleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminNewArticleRoute: typeof AuthenticatedAdminNewArticleRoute
  AuthenticatedAdminNewPdfRoute: typeof AuthenticatedAdminNewPdfRoute
  AuthenticatedAdminNewVideoRoute: typeof AuthenticatedAdminNewVideoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminNewArticleRoute: AuthenticatedAdminNewArticleRoute,
  AuthenticatedAdminNewPdfRoute: AuthenticatedAdminNewPdfRoute,
  AuthenticatedAdminNewVideoRoute: AuthenticatedAdminNewVideoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface WiedzaCategoryRouteChildren {
  WiedzaCategorySlugRoute: typeof WiedzaCategorySlugRoute
}

const WiedzaCategoryRouteChildren: WiedzaCategoryRouteChildren = {
  WiedzaCategorySlugRoute: WiedzaCategorySlugRoute,
}

const WiedzaCategoryRouteWithChildren = WiedzaCategoryRoute._addFileChildren(
  WiedzaCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  PremiumRoute: PremiumRoute,
  WiedzaCategoryRoute: WiedzaCategoryRouteWithChildren,
  WiedzaIndexRoute: WiedzaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
